/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author taxia
 */

public class FutureValueGUI extends javax.swing.JFrame {

    /**
     * Creates new form FutureValueGUI
     */
    public FutureValueGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel lbinvestement = new javax.swing.JLabel();
        textinvestement = new javax.swing.JTextField();
        javax.swing.JLabel lbrate = new javax.swing.JLabel();
        textrate = new javax.swing.JTextField();
        lbWelcome = new javax.swing.JLabel();
        javax.swing.JButton btnOK = new javax.swing.JButton();
        javax.swing.JButton btnClear = new javax.swing.JButton();
        lbyears = new javax.swing.JLabel();
        textyears = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setMinimumSize(new java.awt.Dimension(498, 438));

        lbinvestement.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lbinvestement.setText("Investement");

        textinvestement.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        textinvestement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textinvestementActionPerformed(evt);
            }
        });

        lbrate.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lbrate.setText("Rate");

        textrate.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N

        lbWelcome.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N

        btnOK.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lbyears.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lbyears.setText("Years");

        textyears.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textinvestement)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbyears)
                    .addComponent(lbrate)
                    .addComponent(lbinvestement))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textrate, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textyears, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClear, btnOK});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbinvestement, lbrate, lbyears});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textrate, textyears});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbinvestement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textinvestement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbrate)
                .addGap(18, 18, 18)
                .addComponent(textrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbyears)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textyears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClear, btnOK});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbinvestement, lbrate, lbyears});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textrate, textyears});

        lbinvestement.getAccessibleContext().setAccessibleName("Investement");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
      
      double inv = Double.parseDouble(textinvestement.getText());  
      double rate =Double.parseDouble(textrate.getText());
      int years = Integer.parseInt(textyears.getText());
      double monthlyinv=(rate/12)/100;
      double futureinv=0;
      for (int i=0; i < years*12; i++)
		{
		 futureinv = (futureinv + inv) * (1+monthlyinv);
		}
      lbWelcome.setText("The total Investement is " +futureinv);
      
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       textinvestement.setText("");
       textrate.setText("");
       textyears.setText("");
       lbWelcome.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void textinvestementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textinvestementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textinvestementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FutureValueGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JLabel lbyears;
    private javax.swing.JTextField textinvestement;
    private javax.swing.JTextField textrate;
    private javax.swing.JTextField textyears;
    // End of variables declaration//GEN-END:variables
}
