/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "erg1.h"

bool_t
xdr_int_vector (XDR *xdrs, int_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->array, sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_float_vector (XDR *xdrs, float_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int_vector (xdrs, &objp->vector))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_intpair (XDR *xdrs, intpair *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_floatvec (XDR *xdrs, floatvec *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->array, sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}
